steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - "-m"
      - "rsync"
      - "-r"
      - "-d"
      - "jobs/"
      - "gs://adventureworks-code-bc/pyspark-jobs/"

timeout: "600s"

options:
  logging: CLOUD_LOGGING_ONLY
